# Generated by Django 4.2 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0122_alter_draftissue_assignees_alter_issue_assignees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workspace",
            name="singleton_key",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                check=models.Q(("singleton_key", True)),
                name="workspace_singleton_key_must_be_true",
            ),
        ),
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.UniqueConstraint(
                fields=("singleton_key",),
                name="workspace_only_one",
            ),
        ),
    ]
