# Generated by Django 4.2 on 2026-08-24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0123_workspace_singleton"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="last_workspace_id",
        ),
    ]
