# Generated by Django 4.2 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0124_remove_profile_last_workspace_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                check=models.Q(("deleted_at__isnull", True)),
                name="workspace_cannot_be_soft_deleted",
            ),
        ),
    ]
