# Generated by Django 4.2 on 2026-08-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0124_remove_profile_last_workspace_id"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workspace",
            constraint=models.CheckConstraint(
                check=models.Q(("deleted_at__isnull", True)),
                name="workspace_cannot_be_soft_deleted",
            ),
        ),
        migrations.AlterField(
            model_name="workspace",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner_workspace",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
