# Generated by Django 5.2 on 2026-08-25

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("db", "0125_protect_singleton_workspace"),
    ]

    operations = [
        migrations.DeleteModel(name="DeviceSession"),
        migrations.DeleteModel(name="Device"),
        migrations.DeleteModel(name="Account"),
        migrations.DeleteModel(name="SocialLoginConnection"),
        migrations.DeleteModel(name="WorkspaceMemberInvite"),
        migrations.DeleteModel(name="ProjectMemberInvite"),
        migrations.CreateModel(
            name="IdentitySource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("provider", models.CharField(choices=[("slack", "Slack"), ("discord", "Discord")], max_length=32)),
                ("external_organization_id", models.CharField(max_length=255)),
                ("external_organization_name", models.CharField(max_length=255)),
                ("external_organization_domain", models.CharField(blank=True, default="", max_length=255)),
                ("external_organization_icon_url", models.TextField(blank=True, default="")),
                ("encrypted_access_token", models.TextField(blank=True, default="")),
                ("service_account_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked"), ("error", "Error")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("generation", models.PositiveBigIntegerField(default=1)),
                ("connected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("metadata_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.TextField(blank=True, default="")),
                ("sync_error_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identitysource_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identitysource_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_source",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "identity_sources",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "external_organization_id"),
                        name="identity_source_unique_provider_organization",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        name="identity_source_cannot_soft_delete",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("external_user_id", models.CharField(max_length=255)),
                ("profile", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("workspace_role", models.PositiveSmallIntegerField(default=5)),
                ("source_updated_at", models.BigIntegerField(default=0)),
                ("source_generation", models.PositiveBigIntegerField(default=1)),
                ("authoritative_synced_at", models.DateTimeField(blank=True, null=True)),
                ("snapshot_absent_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="externalidentity_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="db.identitysource",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="externalidentity_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "external_identities",
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_user_id"),
                        name="external_identity_unique_source_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        name="external_identity_cannot_soft_delete",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SlackEventReceipt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("team_id", models.CharField(db_index=True, max_length=64)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("source_generation", models.PositiveBigIntegerField(default=0)),
                ("event_time", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("dead_letter", "Dead letter"),
                        ],
                        db_index=True,
                        default="received",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slackeventreceipt_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_event_receipts",
                        to="db.identitysource",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slackeventreceipt_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={"db_table": "slack_event_receipts", "ordering": ("-received_at",)},
        ),
        migrations.CreateModel(
            name="SlackUserTombstone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("external_user_id", models.CharField(max_length=255)),
                ("source_updated_at", models.BigIntegerField(default=0)),
                ("source_generation", models.PositiveBigIntegerField(default=1)),
                ("snapshot_terminal_at", models.DateTimeField(blank=True, null=True)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slackusertombstone_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_user_tombstones",
                        to="db.identitysource",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="slackusertombstone_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "db_table": "slack_user_tombstones",
                "ordering": ("-observed_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_user_id"),
                        name="slack_user_tombstone_unique_source_user",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        name="slack_user_tombstone_cannot_soft_delete",
                    ),
                ],
            },
        ),
    ]
