# Generated by Django 5.2 on 2026-08-25

from django.db import migrations, models

import plane.db.models.project


def remove_page_data(apps, schema_editor):
    FileAsset = apps.get_model("db", "FileAsset")
    UserFavorite = apps.get_model("db", "UserFavorite")
    UserRecentVisit = apps.get_model("db", "UserRecentVisit")
    DeployBoard = apps.get_model("db", "DeployBoard")

    FileAsset.objects.filter(entity_type="PAGE_DESCRIPTION").delete()
    UserFavorite.objects.filter(entity_type__iexact="page").delete()
    UserRecentVisit.objects.filter(entity_name__iexact="page").delete()
    DeployBoard.objects.filter(entity_name__iexact="page").delete()

    for model_name in ("ProjectMember", "ProjectUserProperty"):
        model = apps.get_model("db", model_name)
        for record in model.objects.exclude(preferences={}).iterator(chunk_size=500):
            preferences = dict(record.preferences or {})
            preferences.pop("pages", None)
            navigation = preferences.get("navigation")
            if isinstance(navigation, dict):
                navigation = dict(navigation)
                if navigation.get("default_tab") == "pages":
                    navigation["default_tab"] = "work_items"
                hidden_items = navigation.get("hide_in_more_menu")
                if isinstance(hidden_items, list):
                    navigation["hide_in_more_menu"] = [item for item in hidden_items if item != "pages"]
                preferences["navigation"] = navigation
            record.preferences = preferences
            record.save(update_fields=["preferences"])


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0127_remove_local_identity_fields"),
    ]

    operations = [
        migrations.RunPython(remove_page_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="project",
            name="page_view",
        ),
        migrations.RemoveField(
            model_name="fileasset",
            name="page",
        ),
        migrations.AlterField(
            model_name="projectmember",
            name="preferences",
            field=models.JSONField(default=plane.db.models.project.get_default_preferences),
        ),
        migrations.AlterField(
            model_name="projectuserproperty",
            name="preferences",
            field=models.JSONField(default=plane.db.models.project.get_default_preferences),
        ),
        migrations.DeleteModel(name="PageVersion"),
        migrations.DeleteModel(name="PageLog"),
        migrations.DeleteModel(name="PageLabel"),
        migrations.DeleteModel(name="ProjectPage"),
        migrations.DeleteModel(name="Page"),
    ]
