# Generated by Django 5.2 on 2026-08-25

from django.db import migrations


REMOVED_EMAIL_TASKS = (
    "plane.bgtasks.cleanup_task.delete_email_notification_logs",
    "plane.bgtasks.email_notification_task.stack_email_notification",
)


def remove_email_periodic_tasks(apps, _schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(task__in=REMOVED_EMAIL_TASKS).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0128_remove_pages"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(remove_email_periodic_tasks, migrations.RunPython.noop),
        migrations.DeleteModel(name="EmailNotificationLog"),
        migrations.DeleteModel(name="UserNotificationPreference"),
    ]
