# Generated by Django 4.2 on 2026-08-24

from django.db import migrations


def remove_workspace_creation_configuration(apps, schema_editor):
    InstanceConfiguration = apps.get_model("license", "InstanceConfiguration")
    InstanceConfiguration.objects.filter(key="DISABLE_WORKSPACE_CREATION").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("license", "0006_instance_is_current_version_deprecated"),
    ]

    operations = [
        migrations.RunPython(
            remove_workspace_creation_configuration,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="InstanceAdmin",
        ),
    ]
