# Generated by Django 4.2 on 2026-08-24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("license", "0007_unify_workspace_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="is_signup_screen_visited",
        ),
    ]
