# Generated by Django 5.2 on 2026-08-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("license", "0008_remove_instance_signup_screen_visited"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="singleton_key",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddConstraint(
            model_name="instance",
            constraint=models.CheckConstraint(
                condition=models.Q(("singleton_key", True)),
                name="instance_singleton_key_must_be_true",
            ),
        ),
        migrations.AddConstraint(
            model_name="instance",
            constraint=models.CheckConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                name="instance_cannot_be_soft_deleted",
            ),
        ),
        migrations.AddConstraint(
            model_name="instance",
            constraint=models.UniqueConstraint(
                fields=("singleton_key",),
                name="instance_only_one",
            ),
        ),
    ]
