# Generated by Django 5.2 on 2026-08-25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("license", "0010_remove_instance_configuration"),
    ]

    operations = [
        migrations.RemoveField(model_name="instance", name="whitelist_emails"),
        migrations.RemoveField(model_name="instance", name="domain"),
        migrations.RemoveField(model_name="instance", name="namespace"),
        migrations.RemoveField(model_name="instance", name="is_support_required"),
        migrations.RemoveField(model_name="instance", name="is_verified"),
        migrations.RemoveField(model_name="instance", name="is_test"),
        migrations.RemoveField(
            model_name="instance",
            name="is_current_version_deprecated",
        ),
        migrations.DeleteModel(name="ChangeLog"),
    ]
